name: Build

on: 
  push:
    branches:
      - master

jobs:
  
  buildTestRelease:

    strategy:
      matrix:
        #os: [ windows-latest, ubuntu-latest, macos-latest ]
        os: [ ubuntu-latest ]
        node_version: [12.x]
        dotnet_version: ['2.1.607']
      fail-fast: false

    runs-on: ${{ matrix.os }}
    
    env:
      PROJECT_NAME: 'action-release'

    steps:

    - uses: actions/checkout@v1
      name: Checkout

    - name: Setup Node.js (${{ matrix.node_version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Version
      run: |
        echo "::set-env name=VERSION::$(npm run version --silent)"

    # - name: Changelog
    #   id: changelog
    #   run: |
    #     npm run changelog

    - name: Release
      uses: sondreb/action-release@master
      with:
        verbose: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: "action.js;README.md"
        draft: true
        prerelease: true
        body: 'A little test - some updated text!'
        #body: ${{outputs.changelog.}}
        name: "Draft Release (Release ${{env.VERSION}})"
        tag: v${{env.VERSION}}
